[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "resend", "puppeteer"]
  included_files = ["src/utils/**", "node_modules/@sparticuz/chromium/**", "node_modules/resend/**", "node_modules/puppeteer/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200